### ISSUE TITLE
Lab 5, Challenge Question 9

### ISSUE THREAD

**Issue by bpiontek** [Watts-College/paf-510-template#15]
The provided code for Lab 5, Challenge Question 9 is:

> m4 <- lm( salary ~ male + female + white + minority - 1, data=dat  )

> stargazer( m4, type="html", digits=0,
           intercept.bottom = FALSE,
           omit.stat = c("ser","f","rsq","adj.rsq"),
           covariate.labels = c("d1: male", 
                                "d2: female",
                                "d3: white",
                                "d4: minority") )

To me, this looks very much like the code from page 17 of the PowerPoint from the lecture, which allows for comparisons between group means:

> lm( math ~ d.sub.tfa + d.sub.reg + d.urb.tfa + d.urb.reg – 1 )

I would think that this would mean that we can run the m4, as the question askes. However, when I run the code, the results for d1 and d2 seem to make intuitive sense, but those for d3 and d4 do not (which I guess would mean that we could run the model, but it's not useful/accurate), and I can't figure out why. 

> Dependent variable:
salary
d1: male	92,342***
(567)
d2: female	99,195***
(536)
d3: white	-4,096***
(630)
d4: minority	
Observations	1,000
Note:	p<0.1; p<0.05; p<0.01

Can you help me understand what I'm missing?

**Comment by youngjaewon** [comment]
@bpiontek 

My response to your question could provide too many hints, but I will answer anyway because this is a challenge (optional) question. The two regression models look similar, but there is an important difference. 

`m4 <- lm( salary ~ male + female + white + minority - 1, data=dat )
`

This model exhibits a perfect multicollinearity problem because it is possible to create one dummy variable by combining the other three dummy variables linearly. For instance, by subtracting the "white" dummy variable from the sum of "male" and "female," we obtain "1 - white," which represents the category "minority." This means that among the four dummy variables, only three of them provide unique information, as the fourth one does not contribute any unique information.

`lm( math ~ d.sub.tfa + d.sub.reg + d.urb.tfa + d.urb.reg – 1 )
`

However, in the model mentioned above, it's not possible to create a single dummy variable by combining the other three dummy variables linearly. This is because the sum of "d.sub.tfa" and "d.sub.reg" doesn't equal one. Each of the four variables provides unique information. As a result, there is no issue of multicollinearity.

> However, when I run the code, the results for d1 and d2 seem to make intuitive sense, but those for d3 and d4 do not (which I guess would mean that we could run the model, but it's not useful/accurate), and I can't figure out why.

The value of "d3" is -4096, which doesn't represent the group mean. This discrepancy arises because the "minority" variable is automatically excluded as a reference category due to multicollinearity. Therefore, the coefficient for "white" indicates that, on average, white individuals have a salary that is $4,096 lower than that of the minority group.

**Comment by bpiontek** [comment]
Thank you! This helps _tremendously_.
