### ISSUE TITLE
Numerator or Denominator: Conflicting Explanations in PDFs

### ISSUE THREAD

**Issue by mjhsu135** [Watts-College/paf-510-template#49]
In PDFs 02 (Partitioning Variance) and 03 (Standard Errors) there is a section that is exactly the same except for the fact that one emphasizes the numerator and one emphasizes the denominator. Which one is the one that shows the unexplained portion of the standard error?

Partitioning Variance PDF:
<img width="591" alt="Screenshot 2024-08-31 at 8 51 21 PM" src="https://github.com/user-attachments/assets/06a95d86-fa6f-419c-922f-a9919a77e9ef">

Standard Errors PDF:
<img width="580" alt="Screenshot 2024-08-31 at 8 51 41 PM" src="https://github.com/user-attachments/assets/37621fb1-ea72-4b6d-a934-4ab57ff18243">

**Comment by nickmcmullen** [comment]
@mjhsu135 thanks for bringing this up. It's numerator. 

A helpful way to think about it... if the residual (unexplained variance) is greater, the SE of the slope (and thus our confidence interval) will be larger because we are more unsure about the true value of b1. Larger numerator with constant denominator (total variability) = larger final result. 

on p. 21 of PDF 02 and p. 9 of PDF 03, there are more intuitive/conceptual definitions with less algebra.

<img width="1019" alt="Screenshot 2024-09-02 at 5 47 33 AM" src="https://github.com/user-attachments/assets/b5591979-1a8d-49e1-8ea3-0d8bae921bb7">
