### ISSUE TITLE
Lab #3 Questions 5-1

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-510-template#5]
Hi Professor, for the questions asking us to see which control variable would change the slope of caffeine if removed from the model and which would result in a larger standard error associated with caffeine if removed from the model?

How would we be able to calculate this in order to be able to make those conclusions? 

Thank you!

**Comment by youngjaewon** [comment]
Hi Jasmin,

If I understood your question correctly, you can calculate the change in coefficients by removing the control variable that is being referred to in lab 3. You need to identify the control variable that can change the slope and standard error of the policy variable in the directions.

I recommend that you review the "TWO TYPES OF CONTROL VARIABLES" section of the lecture notes for module 3.

**Comment by jasminacosta** [comment]
Hi Professor, 

if I understand correctly the unexplained reduces the residuals and the explained weakens the relationship between variables? 

I understand it as the heart rate Venn diagram wise is the a portion while caffeine is the c portion.

While trying it out I was looking at what would change the slope of caffeine, I was thinking of the control variable that had the closest relationship to it where it was more correlated to one another. However, I was also thinking if I needed to look at which one had the highest slope that would then impact the slope of caffeine. 

On the other hand, to see which would result in a larger standard error I was thinking of looking at the control variables and seeing which one had a higher standard error. 

I am just unsure exactly how to draw the conclusions I need.

**Comment by youngjaewon** [comment]
Hi Jasmin,

When drawing a correlation structure in lecture notes, it is important to remember that statistically insignificant correlations are simplified as the two circles not overlapping. While statistically insignificant correlations are also weakly correlated (perfectly zero correlation is not possible in real world data), for the purpose of drawing the correlation structure, we simplify statistically insignificant correlations as not overlapping.

Under this simplification, for the removal of a control variable to alter the slope of caffeine on heart rate, that control variable must be (statistically significantly) correlated (or overlapping) with caffeine. There is only one such control variable (see the figrue below).

Furthermore, regarding the standard error, you are mentioning the standard error of the control variable itself. However, you should pay attention to how much the control variable is correlated with caffeine and heart rate instead of the standard error of the control variable itself. Control variables that are correlated with the outcome, but uncorrelated with the policy, increase the standard errors when removed from the model.

![Picture1](https://github.com/Watts-College/paf-510-template/assets/11006642/b414c3e0-0438-4d5c-ba78-6bf4e3a0e8c2)

**Comment by jasminacosta** [comment]
Hi Professor, 

thank you for the clarification and simplifying the concept for me. It makes a lot more sense to me now!
