### ISSUE TITLE
Running Model 1 in R

### ISSUE THREAD

**Issue by vairving** [Watts-College/paf-510-template#51]
I am getting an error "Error in draw_ci(b1, se, plot.title = "Model 1") : could not find function "draw_ci" when I try to run Model 1 in R studio. I am not getting this error for Models 2 and 4. Any suggestions? Thanks!

**Comment by vairving** [comment]
I was able to get model 1 to work by running all chucks and not just the individual chucks, though individual did work for model 2 and 4.

**Comment by nickmcmullen** [comment]
@vairving I assume you ran a chunk that required the function before you ran the chunk that actually defines the function in your R environment. A good rule of thumb if that happens is to go back and look for where "draw_ci" is written and make sure that chunk of code has been run before you proceed. That's why running individually didn't work the first time, but it worked after you ran all the chunks in the document

**Comment by nickmcmullen** [comment]
@vairving if you're all set can you close out this issue to keep the forum tidy? Thanks!
