### ISSUE TITLE
Lab 4 Part 1 and 2 answer doesn't match

### ISSUE THREAD

**Issue by dmkoch9978** [Watts-College/paf-510-template#66]
Hello,

I just calculated bias in parts 1 and 2 as instructed. However, the answers are about .01 off from each other, almost as if the two equations rounded differently. Is this to be expected or did I do something wrong?

Thanks,
Dani

@nickmcmullen
@AntJam-Howell

**Comment by nickmcmullen** [comment]
@dmkoch9978 they'll be close but not exactly the same. This is due to the rounded coefficients from the regression outputs in Part 1.

**Comment by reed441** [comment]
@nickmcmullen So, I'm getting completely different answers for Part 1 and Part 2, and I think it's because I'm reading one of the regression tables incorrectly. For Part 1, I'm using B1 = 0.52 and b1 = -0.05. For Part 2, I did the following model
`m.auxiliary <- lm( ND ~ PSS, data=dat)`

And then from that regression table, I got
`a1 <- 0.05, B2 <- 0.32`

Do you have any suggestions?

**Comment by nickmcmullen** [comment]
@reed441 you have your dependent and independent variables in m.auxiliary swapped

**Comment by reed441** [comment]
@nickmcmullen Wow, I'm dumb and didn't catch that. Thank you lol.

**Comment by dmkoch9978** [comment]
Thanks, Nick!
