### ISSUE TITLE
Question 1, part 2

### ISSUE THREAD

**Issue by ElvisYoh** [Watts-College/paf-510-template#69]
Hello everyone,
I am having difficulties formulating the auxiliary regression model, and my chunk won't render. I proposed a model as PSS = a0 +a1.ND. Please, I need your help to proceed with the assignment. @nickmcmullen @AntJam-Howell

**Comment by nickmcmullen** [comment]
@ElvisYoh please post a screenshot of your code chunk and the error you're seeing

**Comment by ElvisYoh** [comment]
Sir, @nickmcmullen,  this is the code chunk I am trying to run
```{r, results="asis"}
# m.auxiliary <- lm( PSS ~ a0 + a1.ND, data=dat )

stargazer( m.auxiliary,  
           type = "html", digits=2,
           dep.var.caption = "DV: PSS",
           omit.stat = c("rsq","f","ser"),
           notes.label = "Standard errors in parentheses")

a1 <- 
B2 <- 
bias <- 
bias
```

**Comment by nickmcmullen** [comment]
@ElvisYoh your m.auxiliary is wrong. You should be regressing two existing variables from the data on each other to get alpha1. You already know Beta2. As far as I can tell a0 is not a defined variable, unless you have set it to reference something else in your code. Check back on the lecture materials to see which two variables you need in order to create an auxiliary regression model. The omitted variable bias attachment in M4 lecture materials is a good place to start.

**Comment by ElvisYoh** [comment]
Thank you Sir! I will review the material.

**Comment by ElvisYoh** [comment]
@nickmcmullen Sir, do we use use the values of slope in the full model for m.auxiliary ? I have used those values and have some results, but not certain if it is the right way to go.

**Comment by nickmcmullen** [comment]
@ElvisYoh m.auxiliary is its own model, you don't construct it using coefficients from another model. Coefficients from both m.auxiliary and m.full are required to calculate the bias, if that's what you're asking.

**Comment by ElvisYoh** [comment]
@AntJam-Howell @nickmcmullen Good day Sir. I am working on the current assignment, but have not received feedback from assignment in module 04.

**Comment by nickmcmullen** [comment]
@ElvisYoh I'm posting grades for Lab 04 tomorrow. That shouldn't stop you from working on Lab 05 today if you want to

**Comment by ElvisYoh** [comment]
@nickmcmullen Thank you for the information.
