### ISSUE TITLE
Lab 2 question with code 

### ISSUE THREAD

**Issue by leachapman019** [Watts-College/paf-510-template#8]
Hello again! Im back with another question. 
When I try to save my html it won't let me because there is an issue with some lines that contain the github link. Has anyone else had this issue and how can I correct it? Thank you!

**Comment by bpiontek** [comment]
@leachapman019,  I had the same issue this morning, but was able to work around it by saving my completed answers into a text document, reopening the template, and working in a new copy (running the code, pasting my completed answers in, and finishing the assignment). I had no issues in the reopened template. I know that won't solve your root issue, but hopefully you'll be able to do the same so that this issue won't prevent you from being able to finish the lab.
