### ISSUE TITLE
Lab 06: Marginal Effect Question, Probably Overthinking It

### ISSUE THREAD

**Issue by reed441** [Watts-College/paf-510-template#80]
After calculating the marginal effect for each question in Part 1, does that equal the amount of happiness gained or do you need to multiply by the change in income?

**Comment by bjames25221** [comment]
The instructions give the equation to use for each of the three questions

`# replace with model coefficients 
b0 <- 1
b1 <- 1
b2 <- 1

x <- 1.5  # use 15000 if you did not rescale above
happy.15k <- b0 + b1*x + b2*x*x

x <- 2.5  # use 25000 if you did not rescale above
happy.25k <- b0 + b1*x + b2*x*x

happy.25k - happy.15k  # marginal effect of $10k increase at $15k starting salary`

Once you fill out b0, b1, and b2, you can run the chunk and it shows the marginal effect: how much happier someone is when their salary is increased from 15k to 25k. This is done by that last line, where you subtract one result from the other.

* I changed the x <-15 to x <- 1.5 because as one of the instructors told me in a previous answer, 1.5 is the correct number based on the 10000 scale.

**Comment by reed441** [comment]
Okay word, I was overthinking it. Thank you!

Alexandra (Alexi) Reed
Arizona State University | PhD Student
Phone: (916)-813-1153
