### ISSUE TITLE
Lab 6 Concepts

### ISSUE THREAD

**Issue by alizea-alvarez** [Watts-College/paf-510-template#83]
@nickmcmullen @AntJam-Howell 

So, specification bias happens from one of two sources: 1. when outliers shift the slope because they're at either end of the regression line and 2. when we're trying to find a linear relationship between X and Y when the relationship is non-linear. 

We can address 2 using a quadratic regression that squares the X value. Does the quadratic regression equation allow us to capture X's impact on Y when there is a non-linear relationship between the two?

Outliers at either end of the regression line have the biggest impact on the slope (does it bias the slope?) because they result in larger residuals. Outliers at the extremes can increase the slope, which would risk a Type I Error, or a decrease in the slope, which would risk a Type II Error.

Outliers closer to the mean of X bias' the residuals themselves, increasing the standard errors?

I don't know how the outliers impact the slope just by looking at their positioning. I also don't understand how these concepts generally relate to regression analysis. I am lost in the theory behind specification bias, and the lecture notes aren't helping me understand this. A different explanation of the material would be extremely helpful.

**Comment by AntJam-Howell** [comment]
@alizea-alvarez 
Thank you for your post. 

Specification bias arises when a regression model incorrectly represents the relationship between variables. This can occur due to two main reasons:

Incorrect Model Form: If the true relationship between X and Y is non-linear but a linear model is used, it leads to biased estimates. Quadratic models or other non-linear transformations can correct this issue.

Outliers: Extreme outliers, especially at the ends of the X-axis, can disproportionately influence the slope and lead to skewed results, impacting both significance (Type I errors) and precision (Type II errors).

Quadratic Regression for Non-Linearity: Yes, a quadratic regression allows the model to capture the non-linear impact of X on Y by adding a squared term for X. This is particularly useful when the relationship has diminishing or accelerating returns, common in fields like economics and ecology​.

Outliers and the Slope: Outliers at the extremes of X do bias the slope because they produce large residuals that heavily influence the overall fit. These outliers can increase the slope, leading to a false positive (Type I error) or decrease the slope, leading to a false negative (Type II error)​. 

Outliers near the mean of X:  tend to increase the standard errors, impacting the model's precision but not necessarily the slope​(p-09-specification).  Let’s use an example to explain how outliers closer to the mean of X can affect residuals and increase standard errors: Suppose you’re running a regression to predict Y (income) based on X (years of education). Most of your data points fall around the mean (let's say 12 years of education). However, if you have an outlier near the mean (e.g., someone with 12 years of education but an unusually high or low income), this will increase the residual (difference between observed and predicted Y). Since regression minimizes squared residuals, this larger residual increases the overall standard errors, making your estimates less precise. In contrast, if this outlier were farther from the mean of X, its impact would primarily be on the slope rather than just the standard errors.

Impact on Regression Analysis: In general regression analysis, specification bias distorts the relationship between the independent and dependent variables, making inferences unreliable. Correcting for non-linear relationships with appropriate models (like quadratic or logarithmic transformations) and addressing outliers through diagnostic tests are key to mitigating this bias​.
